### ISSUE TITLE
Multithreading crash

### ISSUE THREAD

**Issue by sei-eschwartz** [cmu-sei/pharos#111]
[bug.zip](https://github.com/cmu-sei/pharos/files/4807046/bug.zip)

Command line is something like this:

```
~eschwartz/pharos/build/tools/ooanalyzer/ooanalyzer --allow-
64bit --threads=8 \
          --ignore-serialize-version --serialize $<.serialize \
          --log "APID(all),OOAN(>=INFO)"  -d \
          --per-function-timeout 60 --maximum-memory 100000 -F $@ $<
>$@.log 2>$@.errors
```

**Comment by sei-eschwartz** [comment]
```
#0  0x00007f39be4b79a4 in __lll_lock_elision () from /lib64/libpthread.so.0
#1  0x0000000000459a7b in boost::posix::pthread_mutex_lock (m=0x10080da8) at /data/research/boost/install-1.64/include/boost/thread/pthread/mutex.hpp:62
#2  boost::mutex::lock (this=0x10080da8) at /data/research/boost/install-1.64/include/boost/thread/pthread/mutex.hpp:116
#3  0x000000000045c4f6 in boost::lock_guard<boost::mutex>::lock_guard (this=0x7f39b1e5d988, m_=...) at /data/research/boost/install-1.64/include/boost/thread/lock_guard.hpp:38
#4  0x00007f39cb67e14a in Sawyer::SharedPointer<pharos::SymbolicValue>::acquireOwnership (rawPtr=0x10080da0) at /data/research/rose/install-latest/include/Sawyer/SharedPointer.h:402
#5  0x00007f39cb677db9 in Sawyer::SharedPointer<pharos::SymbolicValue>::SharedPointer (this=0x7f39b1e5da28, other=...) at /data/research/rose/install-latest/include/Sawyer/SharedPointer.h:106
#6  0x00007f39cb96107e in pharos::SingleThreadedAnalysisCallbacks::readMemory (this=0x7f39a0418880, rops=..., saddr=...) at ../libpharos/riscops.cpp:237
#7  0x00007f39cb9603ef in pharos::SymbolicRiscOperators::readMemory (this=0x7f39a0807710, segreg=..., addr=..., dflt=..., cond=...) at ../libpharos/riscops.cpp:173
#8  0x00007f39c6755ffe in Rose::BinaryAnalysis::InstructionSemantics2::BaseSemantics::Dispatcher::read(SgAsmExpression*, unsigned long, unsigned long) () from /data/research/rose/install-latest/lib/librose.so.1
#9  0x00007f39c67e05f1 in Rose::BinaryAnalysis::InstructionSemantics2::X86::IP_push::p(Rose::BinaryAnalysis::InstructionSemantics2::DispatcherX86*, Rose::BinaryAnalysis::InstructionSemantics2::BaseSemantics::RiscOperators*, SgAsmX86Instruction*, std::vector<SgAsmExpression*, std::allocator<SgAsmExpression*> > const&) () from /data/research/rose/install-latest/lib/librose.so.1
#10 0x00007f39c67c55b4 in Rose::BinaryAnalysis::InstructionSemantics2::X86::InsnProcessor::process(boost::shared_ptr<Rose::BinaryAnalysis::InstructionSemantics2::BaseSemantics::Dispatcher> const&, SgAsmInstruction*) () from /data/research/rose/install-latest/lib/librose.so.1
#11 0x00007f39c6754a10 in Rose::BinaryAnalysis::InstructionSemantics2::BaseSemantics::Dispatcher::processInstruction(SgAsmInstruction*) () from /data/research/rose/install-latest/lib/librose.so.1
#12 0x00007f39cb73ab00 in pharos::BlockAnalysis::analyze (this=0x7f39a07dbe48, with_context=true) at ../libpharos/defuse.cpp:416
#13 0x00007f39cb74797c in pharos::DUAnalysis::process_block_with_limit (this=0x7f39a0418560, vertex=0) at ../libpharos/defuse.cpp:2028
#14 0x00007f39cb748688 in pharos::DUAnalysis::loop_over_cfg (this=0x7f39a0418560) at ../libpharos/defuse.cpp:2184
#15 0x00007f39cb748c1a in pharos::DUAnalysis::solve_flow_equation_iteratively (this=0x7f39a0418560) at ../libpharos/defuse.cpp:2235
#16 0x00007f39cb73cbdb in pharos::DUAnalysis::DUAnalysis (this=0x7f39a0418560, ds_=..., f=...) at ../libpharos/defuse.cpp:721
#17 0x00007f39cb942b3b in pharos::PDG::PDG (this=0x7f39a0418550, ds_=..., f=...) at ../libpharos/pdg.cpp:10
#18 0x00007f39cb7a8026 in std::make_unique<pharos::PDG, pharos::DescriptorSet&, pharos::FunctionDescriptor&> (__args#0=..., __args#1=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/unique_ptr.h:831
#19 0x00007f39cb79fa2f in pharos::FunctionDescriptor::_get_pdg (this=0x13928348) at ../libpharos/funcs.cpp:943
#20 0x00007f39cb79f812 in pharos::FunctionDescriptor::get_pdg (this=0x13928348) at ../libpharos/funcs.cpp:919
#21 0x00007f39cb880127 in pharos::OOAnalyzer::visit (this=0x7ffe2f647550, fd=0x13928348) at ../libpharos/ooanalyzer.cpp:176
#22 0x00007f39cb6dcc2e in pharos::BottomUpAnalyzer::<lambda(size_t, pharos::FunctionDescriptor*)>::operator()(size_t, pharos::FunctionDescriptor *) const (__closure=0x7ffe2f646f30, fd=0x13928348) at ../libpharos/bua.cpp:119
#23 0x00007f39cb6dcf4e in pharos::BottomUpAnalyzer::<lambda(auto:1, const string&)>::<lambda(size_t, pharos::FunctionDescriptor*)>::operator()(size_t, pharos::FunctionDescriptor *) const (this=0x7f39b1e5eb80, s=124, fd=0x13928348) at ../libpharos/bua.cpp:134
#24 0x00007f39cb6e1d8e in Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> >::worker(pharos::BottomUpAnalyzer::<lambda(auto:1, const string&)>::<lambda(size_t, pharos::FunctionDescriptor*)>) (this=0x7ffe2f646d90, functor=...) at /data/research/rose/install-latest/include/Sawyer/ThreadWorkers.h:234
#25 0x00007f39cb6e0f95 in Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> >::startWorker(Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> > *, pharos::BottomUpAnalyzer::<lambda(auto:1, const string&)>::<lambda(size_t, pharos::FunctionDescriptor*)>) (self=0x7ffe2f646d90, functor=...)
    at /data/research/rose/install-latest/include/Sawyer/ThreadWorkers.h:210
#26 0x00007f39cb6e351e in boost::_bi::list2<boost::_bi::value<Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> >*>, boost::_bi::value<pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> > >::operator()<void (*)(Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>]::<lambda(size_t, pharos::FunctionDescriptor*)> >*, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>]::<lambda(size_t, pharos::FunctionDescriptor*)>), boost::_bi::list0>(boost::_bi::type<void>, void (*&)(Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> > *, pharos::BottomUpAnalyzer::<lambda(auto:1, const string&)>::<lambda(size_t, pharos::FunctionDescriptor*)>), boost::_bi::list0 &, int) (this=0x15c689d0, 
    f=@0x15c689c8: 0x7f39cb6e0f61 <Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> >::startWorker(Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> > *, pharos::BottomUpAnalyzer::<lambda(auto:1, const string&)>::<lambda(size_t, pharos::FunctionDescriptor*)>)>, a=...)
    at /data/research/boost/install-1.64/include/boost/bind/bind.hpp:319
#27 0x00007f39cb6e3475 in boost::_bi::bind_t<void, void (*)(Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> >*, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)>), boost::_bi::list2<boost::_bi::value<Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> >*>, boost::_bi::value<pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> > > >::operator()(void) (this=0x15c689c8) at /data/research/boost/install-1.64/include/boost/bind/bind.hpp:1294
#28 0x00007f39cb6e341a in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> >*, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)>), boost::_bi::list2<boost::_bi::value<Sawyer::ThreadWorkers<Sawyer::Container::Graph<pharos::FunctionDescriptor*, Sawyer::Nothing, pharos::FunctionDescriptor*, Sawyer::Container::GraphEdgeNoKey<Sawyer::Nothing>, Sawyer::DefaultAllocator>, pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> >*>, boost::_bi::value<pharos::BottomUpAnalyzer::analyze()::<lambda(auto:1, const string&)> [with auto:1 = pharos::BottomUpAnalyzer::analyze()::<lambda(size_t, pharos::FunctionDescriptor*)>; std::string = std::basic_string<char>]::<lambda(size_t, pharos::FunctionDescriptor*)> > > > >::run(void) (this=0x15c68810) at /data/research/boost/install-1.64/include/boost/thread/detail/thread.hpp:116
#29 0x00007f39c1ff5485 in thread_proxy () from /data/research/boost/install-latest/lib/libboost_thread.so.1.64.0
#30 0x00007f39be4aeea5 in start_thread () from /lib64/libpthread.so.0
#31 0x00007f39be1d78cd in clone () from /lib64/libc.so.6
```

**Comment by sei-mwd** [comment]
Bug only appeared in development code and seems to be fixed there.  Never made it to github.
