### ISSUE TITLE
Ghidra plugin crashes

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#79]
I used ooanalyzer using the docker image, and upon pulling the json file into ghidra, after some processing - the plugin crashes with this error message:
```
Uncaught Exception! 
RuntimeException - Timed-out waiting to run a Swing task--potential deadlock!
java.lang.RuntimeException: Timed-out waiting to run a Swing task--potential deadlock!
	at ghidra.util.Swing.runNow(Swing.java:180)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at ghidra.framework.data.DomainObjectChangeSupport.flush(DomainObjectChangeSupport.java:143)
	at ghidra.framework.data.DomainObjectAdapter.flushEvents(DomainObjectAdapter.java:246)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.taskFailed(ToolTaskManager.java:451)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:143)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: ghidra.util.exception.UnableToSwingException: Timed-out waiting for Swing thread lock in 20 SECONDS
	at ghidra.util.Swing.waitFor(Swing.java:259)
	at ghidra.util.Swing.runNow(Swing.java:238)
	at ghidra.util.Swing.runNow(Swing.java:166)
	... 7 more

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Java\jdk-14.0.1
JVM Version: Oracle Corporation 14.0.1
OS: Windows 8.1 6.3 amd64
Workstation: jan

```
 I also tried on Linux to make sure it was not a platform issue. The message is a bit different
```
Uncaught Exception! 
java.lang.NullPointerException
	at ghidra.program.database.data.StructureDB.replaceAtOffset(StructureDB.java:1052)
	at ooanalyzer.OOAnalyzer.analyzeMembers(OOAnalyzer.java:1148)
	at ooanalyzer.OOAnalyzer.lambda$analyzeClasses$8(OOAnalyzer.java:396)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at ooanalyzer.OOAnalyzer.analyzeClasses(OOAnalyzer.java:394)
	at ooanalyzer.OOAnalyzer.execute(OOAnalyzer.java:230)
	at ooanalyzer.OOAnalyzerGhidraPlugin.configureAndExecute(OOAnalyzerGhidraPlugin.java:87)
	at ooanalyzer.OOAnalyzerGhidraPlugin$1.actionPerformed(OOAnalyzerGhidraPlugin.java:109)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.MenuBarMenuHandler$1.run(MenuBarMenuHandler.java:78)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /usr/lib/jvm/java-11-openjdk-amd64
JVM Version: Private Build 11.0.5
OS: Linux 5.3.0-050300-generic amd64
Workstation: jan-17Z990-R-AAS8U1



```

- I re-did the Ghidra analysis of the program to make sure my renaming of functions/variables did not affect anything.
- I re-ran ooanalyzer to make a new json file, in case it got corrupted.
- checking "use ooanalyzer namespace" or not has no effect.

what else can I try?
 [V9.zip](https://github.com/cmu-sei/pharos/files/4573089/V9.zip)

**Comment by sei-eschwartz** [comment]
This looks like two separate problems to me.  The Windows one looks like a timeout.  I think plugins are supposed to call an API every so often to tell Ghidra they're still working.  I'm not sure if we do that or not, but will check.  You could try setting SWING_TIMEOUT_SECONDS_PROPERTY (see https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/Utility/src/main/java/ghidra/util/Swing.java#L38).

The second problem looks more like a straight-forward bug.  It's unclear why it would trigger on Linux and not Windows.  Maybe it just happened to trigger before the timeout exception fired?

I'll look more later today.

**Comment by janbbeck** [comment]
Small update: If I run the plugin before doing the Ghidra code analysis, it seems to work...

**Comment by jeffgennari** [comment]
I updated the plugin to catch the null pointer while I investigate.

**Comment by jeffgennari** [comment]
Can you share the executable that you ran this on? The JSON is well-formed from what i can tell.

**Comment by sei-eschwartz** [comment]
I got the timeout error on Ghidra 9.1.2 Linux.  My theory is this: OOanalyzer plugin makes changes to something that triggers some Ghidra analysis which is unable to run for a long time, and this causes the deadlock.  My backtrace was a little different, but it seemed to be called from "auto analysis" code, which is interesting because I waited for the auto analysis to complete before running the OOAnalyzer import.

I am re-running and will include my backtrace...

**Comment by sei-eschwartz** [comment]
Oops, I got the same backtrace as @janbbeck.  I was looking at the timeout one so I thought it was different.

**Comment by jeffgennari** [comment]
I'm able to reproduce this, but it is a deep exception somewhere in Ghidra. At least part of the issue is that this is an MFC program with many externally defined classes. We'll continue to investigate.

**Comment by sei-eschwartz** [comment]
@janbbeck Were you able to get things to work with the new patch?  We're still working on the underlying problems.

**Comment by janbbeck** [comment]
I am hesitant to say no, because I am not sure what 'work' means. I am not familiar with what it should be doing, yet. 

That being said, here is what I found:

If I try to run it on an executable that has already been analyzed, it runs for a while and then shows the error message eventually. As far as I can tell no namespace or classes have been added at that point, so I would lean to say it does not work.

If I run it on a non-analyzed executable, I get a success message about ~1300 found classes. Inspection of many of them found them all to be empty.

I would like to point out that the IDA plugin also fails. A lot of messages show on the output window right away, but then it hangs forever with the "please wait - running python script" progress window, slowly leaking memory over the next few days....

**Comment by sei-eschwartz** [comment]
I think it's safe to say that is "not working" :rofl: 

You tried using the version that catches the null pointer exception, right?  When I run that after analysis, I do get GUI lags and a timeout exception on the console, but it eventually does print a success message and there are classes present.  Anyway, try this branch: https://github.com/edmcman/pharos/tree/ghidra-plugin

It should solve the timeout exception and adds status reporting.

**Comment by janbbeck** [comment]
Well, it looks like I built the null pointer version, but forgot to load it into ghidra :P

Anyway, I just replaced it with your latest branch as suggested above, and the progress bar is a great improvement.
On linux, there is just the bar ( still good!), but on windows there is the bar and a count inside of the bar like `(222 out of 1315)`. I guess that is platform specific stuff you have no influence over?

On windows, I dont get a success message though. Eventually:
```
An unexpected error occurred while processing the command: OOAnalyzer Import
java.lang.IllegalArgumentException: Data type *INVALID* can't contain itself.
	at ghidra.program.database.data.CompositeDB.checkAncestry(CompositeDB.java:265)
	at ghidra.program.database.data.StructureDB.doReplaceWithUnaligned(StructureDB.java:1194)
	at ghidra.program.database.data.StructureDB.doReplaceWith(StructureDB.java:1133)
	at ghidra.program.database.data.DataTypeManagerDB.createStructure(DataTypeManagerDB.java:2160)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:2099)
	at ghidra.program.database.data.DataTypeManagerDB.resolveNoSourceDataType(DataTypeManagerDB.java:847)
	at ghidra.program.database.data.DataTypeManagerDB.resolve(DataTypeManagerDB.java:735)
	at ghidra.program.database.data.DataTypeManagerDB.addDataType(DataTypeManagerDB.java:1005)
	at ooanalyzer.OOAnalyzer.updateTypeManager(OOAnalyzer.java:1335)
	at ooanalyzer.OOAnalyzer.analyzeClasses(OOAnalyzer.java:442)
	at ooanalyzer.OOAnalyzerGhidraPlugin$ImportCommand.cmdConfigureAndExecute(OOAnalyzerGhidraPlugin.java:114)
	at ooanalyzer.OOAnalyzerGhidraPlugin$ImportCommand.applyTo(OOAnalyzerGhidraPlugin.java:68)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Java\jdk-14.0.1
JVM Version: Oracle Corporation 14.0.1
OS: Windows 8.1 6.3 amd64
Workstation: jan
```

though there is now an ooanalyzer namespace. And all the `cls_` elements in the tree are empty.

On linux, it completes with a success message, and almost all of those `cls_` elements are properly filled.

**Comment by sei-eschwartz** [comment]
Sigh, you would think the behavior would be the same on Windows since it's all Java...  I'll try to figure out what is going on there.

Also, we are aware of the *INVALID* types and are working on fixing those too.

**Comment by sei-eschwartz** [comment]
Hmm, I just reproduced your above traceback on Linux by importing before analysis.  Did you run analysis first on Windows?

**Comment by janbbeck** [comment]
You had that right. Sorry about that....

**Comment by astrelsky** [comment]
> I got the timeout error on Ghidra 9.1.2 Linux. My theory is this: OOanalyzer plugin makes changes to something that triggers some Ghidra analysis which is unable to run for a long time, and this causes the deadlock. My backtrace was a little different, but it seemed to be called from "auto analysis" code, which is interesting because I waited for the auto analysis to complete before running the OOAnalyzer import.
> 
> I am re-running and will include my backtrace...

You can tell the AutoAnalysisManager to ignore changes until told otherwise for a program being analyzed by invoking AutoAnalysisManager.setIgnoreChanges. You can retrieve the AutoAnalysisManager  using its static method AutoAnalysisManager.getAnalysisManager.

The documentation for this class isn't build by default when building ghidra. Here is a snippit of the method documentation for convienence.

![Capture](https://user-images.githubusercontent.com/46897303/82839143-608a8900-9e9c-11ea-9c0c-5288f6a57ffb.PNG)
